name: horse-person
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pip
  - pip:
      - tensorflow==2.11.0
      - scikeras==0.10.0
      - flask
      - jupyterlab
      - pillow
      - ipykernel
